/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function GLine(props) {
  const { nodes, materials } = useGLTF('./public/subway_map_v4.glb')
//   console.log(nodes)
  function makeStationBig(station){
    for (const node in nodes){
        if (node === station){
            // console.log(node)
        }
    }
  }

  makeStationBig("01_Court_Sq_G")  
  return (
    <group {...props} dispose={null}>
      <group name="Scene">
        <group name="Scene_Collection">
          <group name="MAP">
            <mesh
              name="00_NYC_full_trackmap"
              castShadow
              receiveShadow
              geometry={nodes['00_NYC_full_trackmap'].geometry}
              material={materials.NYC_full_trackmap}
              position={[5.621, 0.021, 1.498]}
              rotation={[0, Math.PI / 2, 0]}
              scale={100}
            />
            <group name="G">
              <group name="G_Stations">
                <mesh
                  name="01_Court_Sq_G"
                  castShadow
                  receiveShadow
                  geometry={nodes['01_Court_Sq_G'].geometry}
                  material={materials['Station_G.001']}
                  position={[5.799, 0.034, 10.29]}
                  rotation={[0, 0.401, 0]}
                  scale={0.2}
                />
                <mesh
                  name="02_21_St_G"
                  castShadow
                  receiveShadow
                  geometry={nodes['02_21_St_G'].geometry}
                  material={materials['Station_G.001']}
                  position={[6.467, 0.034, 11.546]}
                  rotation={[0, 0.593, 0]}
                  scale={0.2}
                />
                <mesh
                  name="03_Greenpoint_Ave_G"
                  castShadow
                  receiveShadow
                  geometry={nodes['03_Greenpoint_Ave_G'].geometry}
                  material={materials['Station_G.001']}
                  position={[9.869, 0.034, 12.496]}
                  rotation={[0, 0.105, 0]}
                  scale={0.2}
                />
                <mesh
                  name="04_Nassau_Av_G"
                  castShadow
                  receiveShadow
                  geometry={nodes['04_Nassau_Av_G'].geometry}
                  material={materials['Station_G.001']}
                  position={[11.668, 0.034, 11.843]}
                  rotation={[0, Math.PI / 9, 0]}
                  scale={0.2}
                />
                <mesh
                  name="05_Metropolitan_Lorimer_G"
                  castShadow
                  receiveShadow
                  geometry={nodes['05_Metropolitan_Lorimer_G'].geometry}
                  material={materials['Station_G.001']}
                  position={[14.807, 0.034, 11.871]}
                  rotation={[0, 0.105, 0]}
                  scale={0.2}
                />
                <mesh
                  name="06_Broadway_G"
                  castShadow
                  receiveShadow
                  geometry={nodes['06_Broadway_G'].geometry}
                  material={materials['Station_G.001']}
                  position={[16.493, 0.034, 11.647]}
                  rotation={[0, 0.105, 0]}
                  scale={0.2}
                />
                <mesh
                  name="07_Flushing_G001"
                  castShadow
                  receiveShadow
                  geometry={nodes['07_Flushing_G001'].geometry}
                  material={materials['Station_G.001']}
                  position={[18.062, 0.034, 11.647]}
                  rotation={[0, 0.035, 0]}
                  scale={0.2}
                />
                <mesh
                  name="08_Myrtle_Willoughby_G"
                  castShadow
                  receiveShadow
                  geometry={nodes['08_Myrtle_Willoughby_G'].geometry}
                  material={materials['Station_G.001']}
                  position={[19.642, 0.034, 11.397]}
                  rotation={[0, 0.175, 0]}
                  scale={0.2}
                />
                <mesh
                  name="09_Bedford_Nostrand_G"
                  castShadow
                  receiveShadow
                  geometry={nodes['09_Bedford_Nostrand_G'].geometry}
                  material={materials['Station_G.001']}
                  position={[20.955, 0.034, 12.316]}
                  rotation={[0, 0.175, 0]}
                  scale={0.2}
                />
                <mesh
                  name="10_Classon_G"
                  castShadow
                  receiveShadow
                  geometry={nodes['10_Classon_G'].geometry}
                  material={materials['Station_G.001']}
                  position={[21.167, 0.034, 13.63]}
                  rotation={[0, 0.175, 0]}
                  scale={0.2}
                />
                <mesh
                  name="11_Clinton_Washington_G"
                  castShadow
                  receiveShadow
                  geometry={nodes['11_Clinton_Washington_G'].geometry}
                  material={materials['Station_G.001']}
                  position={[21.35, 0.034, 15.056]}
                  rotation={[0, 0.175, 0]}
                  scale={0.2}
                />
                <mesh
                  name="12_Fulton_G"
                  castShadow
                  receiveShadow
                  geometry={nodes['12_Fulton_G'].geometry}
                  material={materials['Station_G.001']}
                  position={[21.604, 0.034, 16.62]}
                  rotation={[0, 0.175, 0]}
                  scale={0.2}
                />
                <mesh
                  name="13_Hoyt_Schermerhorn_Sts_ACG"
                  castShadow
                  receiveShadow
                  geometry={nodes['13_Hoyt_Schermerhorn_Sts_ACG'].geometry}
                  material={materials['Station_G.001']}
                  position={[21.239, 0.034, 18.603]}
                  rotation={[-0.004, -0.496, -0.005]}
                  scale={0.2}
                />
                <mesh
                  name="14_Bergen_St_FG"
                  castShadow
                  receiveShadow
                  geometry={nodes['14_Bergen_St_FG'].geometry}
                  material={materials['Station_G.001']}
                  position={[21.933, 0.034, 19.866]}
                  rotation={[-0.004, -0.496, -0.005]}
                  scale={0.2}
                />
                <mesh
                  name="15_Caroll_St_FG"
                  castShadow
                  receiveShadow
                  geometry={nodes['15_Caroll_St_FG'].geometry}
                  material={materials['Station_G.001']}
                  position={[23.562, 0.034, 20.734]}
                  rotation={[-0.004, -0.496, -0.005]}
                  scale={0.2}
                />
                <mesh
                  name="16_Smith_9th_St"
                  castShadow
                  receiveShadow
                  geometry={nodes['16_Smith_9th_St'].geometry}
                  material={materials['Station_G.001']}
                  position={[25.195, 0.034, 20.843]}
                  rotation={[-0.005, -0.69, -0.006]}
                  scale={0.2}
                />
                <mesh
                  name="17_4_Av-9_St_FGR"
                  castShadow
                  receiveShadow
                  geometry={nodes['17_4_Av-9_St_FGR'].geometry}
                  material={materials['Station_G.001']}
                  position={[26.104, 0.034, 19.615]}
                  rotation={[-0.008, 1.027, 0.004]}
                  scale={0.2}
                />
                <mesh
                  name="17_7_Av_FFxG"
                  castShadow
                  receiveShadow
                  geometry={nodes['17_7_Av_FFxG'].geometry}
                  material={materials['Station_G.001']}
                  position={[27.126, 0.034, 17.752]}
                  rotation={[-0.007, 1.005, 0.004]}
                  scale={0.2}
                />
                <mesh
                  name="18_15_St_FG"
                  castShadow
                  receiveShadow
                  geometry={nodes['18_15_St_FG'].geometry}
                  material={materials['Station_G.001']}
                  position={[28.903, 0.034, 17.575]}
                  rotation={[-0.007, 1.005, 0.004]}
                  scale={0.2}
                />
                <mesh
                  name="19_Ft_Hamilton_Pkwy_FG"
                  castShadow
                  receiveShadow
                  geometry={nodes['19_Ft_Hamilton_Pkwy_FG'].geometry}
                  material={materials['Station_G.001']}
                  position={[31.405, 0.034, 16.787]}
                  rotation={[-0.064, 1.509, 0.061]}
                  scale={0.2}
                />
                <mesh
                  name="20_Church_Av_FFxG"
                  castShadow
                  receiveShadow
                  geometry={nodes['20_Church_Av_FFxG'].geometry}
                  material={materials['Station_G.001']}
                  position={[33.119, 0.034, 17.587]}
                  rotation={[-3.114, 1.427, 3.112]}
                  scale={0.2}
                />
              </group>
              <group name="G_Tracks">
                <mesh
                  name="015_21_Court_N"
                  castShadow
                  receiveShadow
                  geometry={nodes['015_21_Court_N'].geometry}
                  material={materials['Station_G.001']}
                  position={[6.162, 0.034, 10.988]}>
                  <mesh
                    name="GN_Instance"
                    castShadow
                    receiveShadow
                    geometry={nodes.GN_Instance.geometry}
                    material={materials['Station_G.001']}
                  />
                </mesh>
                <mesh
                  name="015_Court_21t_S"
                  castShadow
                  receiveShadow
                  geometry={nodes['015_Court_21t_S'].geometry}
                  material={materials['Station_G.001']}
                  position={[6.228, 0.038, 10.992]}>
                  <mesh
                    name="GN_Instance_1"
                    castShadow
                    receiveShadow
                    geometry={nodes.GN_Instance_1.geometry}
                    material={materials['Station_G.001']}
                  />
                </mesh>
                <mesh
                  name="025_21_Greenpoint_S"
                  castShadow
                  receiveShadow
                  geometry={nodes['025_21_Greenpoint_S'].geometry}
                  material={materials['Station_G.001']}
                  position={[6.971, 0.052, 12.404]}>
                  <mesh
                    name="GN_Instance_2"
                    castShadow
                    receiveShadow
                    geometry={nodes.GN_Instance_2.geometry}
                    material={materials['Station_G.001']}
                  />
                </mesh>
                <mesh
                  name="025_Greenpoint_21_N001"
                  castShadow
                  receiveShadow
                  geometry={nodes['025_Greenpoint_21_N001'].geometry}
                  material={materials['Station_G.001']}
                  position={[7.005, 0.052, 12.331]}>
                  <mesh
                    name="GN_Instance_3"
                    castShadow
                    receiveShadow
                    geometry={nodes.GN_Instance_3.geometry}
                    material={materials['Station_G.001']}
                  />
                </mesh>
                <mesh
                  name="035_Greenpoint_Nassau_S"
                  castShadow
                  receiveShadow
                  geometry={nodes['035_Greenpoint_Nassau_S'].geometry}
                  material={materials['Station_G.001']}
                  position={[10.325, 0.031, 13.324]}>
                  <mesh
                    name="GN_Instance_4"
                    castShadow
                    receiveShadow
                    geometry={nodes.GN_Instance_4.geometry}
                    material={materials['Station_G.001']}
                  />
                </mesh>
                <mesh
                  name="035_Nassaue_Greenpoint_N"
                  castShadow
                  receiveShadow
                  geometry={nodes['035_Nassaue_Greenpoint_N'].geometry}
                  material={materials['Station_G.001']}
                  position={[10.308, 0.031, 13.392]}>
                  <mesh
                    name="GN_Instance_5"
                    castShadow
                    receiveShadow
                    geometry={nodes.GN_Instance_5.geometry}
                    material={materials['Station_G.001']}
                  />
                </mesh>
                <mesh
                  name="045_Met_Lor_N001"
                  castShadow
                  receiveShadow
                  geometry={nodes['045_Met_Lor_N001'].geometry}
                  material={materials['Station_G.001']}
                  position={[12.251, 0.073, 12.618]}>
                  <mesh
                    name="GN_Instance_6"
                    castShadow
                    receiveShadow
                    geometry={nodes.GN_Instance_6.geometry}
                    material={materials['Station_G.001']}
                  />
                </mesh>
                <mesh
                  name="045_Met_Lor_Nassau_N"
                  castShadow
                  receiveShadow
                  geometry={nodes['045_Met_Lor_Nassau_N'].geometry}
                  material={materials['Station_G.001']}
                  position={[12.244, 0.073, 12.543]}>
                  <mesh
                    name="GN_Instance_7"
                    castShadow
                    receiveShadow
                    geometry={nodes.GN_Instance_7.geometry}
                    material={materials['Station_G.001']}
                  />
                </mesh>
                <mesh
                  name="055_Bway_Met_Lor_N"
                  castShadow
                  receiveShadow
                  geometry={nodes['055_Bway_Met_Lor_N'].geometry}
                  material={materials['Station_G.001']}
                  position={[15.201, 0.031, 12.641]}>
                  <mesh
                    name="GN_Instance_8"
                    castShadow
                    receiveShadow
                    geometry={nodes.GN_Instance_8.geometry}
                    material={materials['Station_G.001']}
                  />
                </mesh>
                <mesh
                  name="055_Met_Lor_Bway_S"
                  castShadow
                  receiveShadow
                  geometry={nodes['055_Met_Lor_Bway_S'].geometry}
                  material={materials['Station_G.001']}
                  position={[15.213, 0.031, 12.698]}>
                  <mesh
                    name="GN_Instance_9"
                    castShadow
                    receiveShadow
                    geometry={nodes.GN_Instance_9.geometry}
                    material={materials['Station_G.001']}
                  />
                </mesh>
                <mesh
                  name="065_Bway_Flushing_S"
                  castShadow
                  receiveShadow
                  geometry={nodes['065_Bway_Flushing_S'].geometry}
                  material={materials['Station_G.001']}
                  position={[16.944, 0.031, 12.51]}
                  rotation={[0.017, -0.193, -0.002]}>
                  <mesh
                    name="GN_Instance_10"
                    castShadow
                    receiveShadow
                    geometry={nodes.GN_Instance_10.geometry}
                    material={materials['Station_G.001']}
                  />
                </mesh>
                <mesh
                  name="065_Flushing_Bway_N"
                  castShadow
                  receiveShadow
                  geometry={nodes['065_Flushing_Bway_N'].geometry}
                  material={materials['Station_G.001']}
                  position={[16.941, 0.031, 12.459]}
                  rotation={[0.017, -0.193, -0.002]}>
                  <mesh
                    name="GN_Instance_11"
                    castShadow
                    receiveShadow
                    geometry={nodes.GN_Instance_11.geometry}
                    material={materials['Station_G.001']}
                  />
                </mesh>
                <mesh
                  name="075_Flushing_Myr_Wil_S"
                  castShadow
                  receiveShadow
                  geometry={nodes['075_Flushing_Myr_Wil_S'].geometry}
                  material={materials['Station_G.001']}
                  position={[18.601, 0.031, 12.457]}
                  rotation={[0.002, -0.028, 0]}>
                  <mesh
                    name="GN_Instance_12"
                    castShadow
                    receiveShadow
                    geometry={nodes.GN_Instance_12.geometry}
                    material={materials['Station_G.001']}
                  />
                </mesh>
                <mesh
                  name="075_Myr_Wil_Flushing_N"
                  castShadow
                  receiveShadow
                  geometry={nodes['075_Myr_Wil_Flushing_N'].geometry}
                  material={materials['Station_G.001']}
                  position={[18.588, 0.031, 12.399]}
                  rotation={[0.002, -0.028, 0]}>
                  <mesh
                    name="GN_Instance_13"
                    castShadow
                    receiveShadow
                    geometry={nodes.GN_Instance_13.geometry}
                    material={materials['Station_G.001']}
                  />
                </mesh>
                <mesh
                  name="085_Bed_Nos->Myr_Wil_N"
                  castShadow
                  receiveShadow
                  geometry={nodes['085_Bed_Nos->Myr_Wil_N'].geometry}
                  material={materials['Station_G.001']}
                  position={[20.244, 0.017, 12.102]}
                  rotation={[0.002, -0.028, 0]}>
                  <mesh
                    name="GN_Instance_14"
                    castShadow
                    receiveShadow
                    geometry={nodes.GN_Instance_14.geometry}
                    material={materials['Station_G.001']}
                  />
                </mesh>
                <mesh
                  name="085_Myr_Wil->Bed_Nos_S"
                  castShadow
                  receiveShadow
                  geometry={nodes['085_Myr_Wil->Bed_Nos_S'].geometry}
                  material={materials['Station_G.001']}
                  position={[20.197, 0.021, 12.192]}
                  rotation={[0.002, -0.028, 0]}>
                  <mesh
                    name="GN_Instance_15"
                    castShadow
                    receiveShadow
                    geometry={nodes.GN_Instance_15.geometry}
                    material={materials['Station_G.001']}
                  />
                </mesh>
                <mesh
                  name="095_Bed-Nos->Classon_S"
                  castShadow
                  receiveShadow
                  geometry={nodes['095_Bed-Nos->Classon_S'].geometry}
                  material={materials['Station_G.001']}
                  position={[20.126, -0.076, 12.688]}
                  rotation={[-2.232, -1.538, -2.108]}>
                  <mesh
                    name="GN_Instance_16"
                    castShadow
                    receiveShadow
                    geometry={nodes.GN_Instance_16.geometry}
                    material={materials['Station_G.001']}
                  />
                </mesh>
                <mesh
                  name="095_Classon->Bed-Nos_N"
                  castShadow
                  receiveShadow
                  geometry={nodes['095_Classon->Bed-Nos_N'].geometry}
                  material={nodes['095_Classon->Bed-Nos_N'].material}
                  position={[20.182, -0.084, 12.674]}
                  rotation={[-2.232, -1.538, -2.108]}>
                  <mesh
                    name="GN_Instance_17"
                    castShadow
                    receiveShadow
                    geometry={nodes.GN_Instance_17.geometry}
                    material={nodes.GN_Instance_17.material}
                  />
                </mesh>
                <mesh
                  name="105_Classon->Clin_Wash_S"
                  castShadow
                  receiveShadow
                  geometry={nodes['105_Classon->Clin_Wash_S'].geometry}
                  material={materials['Station_G.001']}
                  position={[20.333, -0.069, 14.145]}
                  rotation={[-2.232, -1.538, -2.108]}>
                  <mesh
                    name="GN_Instance_18"
                    castShadow
                    receiveShadow
                    geometry={nodes.GN_Instance_18.geometry}
                    material={materials['Station_G.001']}
                  />
                </mesh>
                <mesh
                  name="105_Clin_Wash->Classon_N"
                  castShadow
                  receiveShadow
                  geometry={nodes['105_Clin_Wash->Classon_N'].geometry}
                  material={materials['Station_G.001']}
                  position={[20.391, -0.067, 14.136]}
                  rotation={[-2.232, -1.538, -2.108]}>
                  <mesh
                    name="GN_Instance_19"
                    castShadow
                    receiveShadow
                    geometry={nodes.GN_Instance_19.geometry}
                    material={materials['Station_G.001']}
                  />
                </mesh>
                <mesh
                  name="115_Fulton->Clin_Wash_N"
                  castShadow
                  receiveShadow
                  geometry={nodes['115_Fulton->Clin_Wash_N'].geometry}
                  material={materials['Station_G.001']}
                  position={[20.599, -0.053, 15.575]}
                  rotation={[-2.232, -1.538, -2.108]}>
                  <mesh
                    name="GN_Instance_20"
                    castShadow
                    receiveShadow
                    geometry={nodes.GN_Instance_20.geometry}
                    material={materials['Station_G.001']}
                  />
                </mesh>
                <mesh
                  name="115_Fulton->Lafeyette_S"
                  castShadow
                  receiveShadow
                  geometry={nodes['115_Fulton->Lafeyette_S'].geometry}
                  material={materials['Station_G.001']}
                  position={[20.546, -0.054, 15.562]}
                  rotation={[-2.232, -1.538, -2.108]}>
                  <mesh
                    name="GN_Instance_21"
                    castShadow
                    receiveShadow
                    geometry={nodes.GN_Instance_21.geometry}
                    material={materials['Station_G.001']}
                  />
                </mesh>
                <mesh
                  name="125_Fulton_St->Hoyt-Shermerhorn_Sts_S"
                  castShadow
                  receiveShadow
                  geometry={nodes['125_Fulton_St->Hoyt-Shermerhorn_Sts_S'].geometry}
                  material={materials['Station_G.001']}
                  position={[20.809, -0.053, 17.198]}
                  rotation={[-2.232, -1.538, -2.108]}>
                  <mesh
                    name="GN_Instance_22"
                    castShadow
                    receiveShadow
                    geometry={nodes.GN_Instance_22.geometry}
                    material={materials['Station_G.001']}
                  />
                </mesh>
                <mesh
                  name="125_Hoyt-Shermerhorn_Sts->Fulton_N"
                  castShadow
                  receiveShadow
                  geometry={nodes['125_Hoyt-Shermerhorn_Sts->Fulton_N'].geometry}
                  material={materials['Station_G.001']}
                  position={[20.868, -0.053, 17.186]}
                  rotation={[-2.232, -1.538, -2.108]}>
                  <mesh
                    name="GN_Instance_23"
                    castShadow
                    receiveShadow
                    geometry={nodes.GN_Instance_23.geometry}
                    material={materials['Station_G.001']}
                  />
                </mesh>
                <mesh
                  name="135_Bergen_St->Hoyt-Shermerhorn_Sts_N"
                  castShadow
                  receiveShadow
                  geometry={nodes['135_Bergen_St->Hoyt-Shermerhorn_Sts_N'].geometry}
                  material={materials['Station_G.001']}
                  position={[20.396, -0.053, 19.1]}
                  rotation={[-2.232, -1.538, -2.108]}>
                  <mesh
                    name="GN_Instance_24"
                    castShadow
                    receiveShadow
                    geometry={nodes.GN_Instance_24.geometry}
                    material={materials['Station_G.001']}
                  />
                </mesh>
                <mesh
                  name="135_Bergen_St->Hoyt-Shermerhorn_Sts_N001"
                  castShadow
                  receiveShadow
                  geometry={nodes['135_Bergen_St->Hoyt-Shermerhorn_Sts_N001'].geometry}
                  material={materials['Station_G.001']}
                  position={[20.336, -0.053, 19.123]}
                  rotation={[-2.232, -1.538, -2.108]}>
                  <mesh
                    name="GN_Instance_25"
                    castShadow
                    receiveShadow
                    geometry={nodes.GN_Instance_25.geometry}
                    material={materials['Station_G.001']}
                  />
                </mesh>
                <mesh
                  name="145_Bergen_St->Caroll_St_S"
                  castShadow
                  receiveShadow
                  geometry={nodes['145_Bergen_St->Caroll_St_S'].geometry}
                  material={materials['Station_G.001']}
                  position={[22.025, -0.053, 20.002]}
                  rotation={[-2.232, -1.538, -2.108]}>
                  <mesh
                    name="GN_Instance_26"
                    castShadow
                    receiveShadow
                    geometry={nodes.GN_Instance_26.geometry}
                    material={materials['Station_G.001']}
                  />
                </mesh>
                <mesh
                  name="145_Caroll_St->Bergen_St_N"
                  castShadow
                  receiveShadow
                  geometry={nodes['145_Caroll_St->Bergen_St_N'].geometry}
                  material={materials['Station_G.001']}
                  position={[22.059, -0.053, 19.951]}
                  rotation={[-2.232, -1.538, -2.108]}>
                  <mesh
                    name="GN_Instance_27"
                    castShadow
                    receiveShadow
                    geometry={nodes.GN_Instance_27.geometry}
                    material={materials['Station_G.001']}
                  />
                </mesh>
                <mesh
                  name="155_Caroll_St->Smith-9_Sts_S"
                  castShadow
                  receiveShadow
                  geometry={nodes['155_Caroll_St->Smith-9_Sts_S'].geometry}
                  material={materials['Station_G.001']}
                  position={[23.664, -0.053, 20.939]}
                  rotation={[-2.232, -1.538, -2.108]}>
                  <mesh
                    name="GN_Instance_28"
                    castShadow
                    receiveShadow
                    geometry={nodes.GN_Instance_28.geometry}
                    material={materials['Station_G.001']}
                  />
                </mesh>
                <mesh
                  name="155_St_Smith-9_Sts->Caroll_N"
                  castShadow
                  receiveShadow
                  geometry={nodes['155_St_Smith-9_Sts->Caroll_N'].geometry}
                  material={materials['Station_G.001']}
                  position={[23.647, -0.053, 20.836]}
                  rotation={[-2.232, -1.538, -2.108]}>
                  <mesh
                    name="GN_Instance_29"
                    castShadow
                    receiveShadow
                    geometry={nodes.GN_Instance_29.geometry}
                    material={materials['Station_G.001']}
                  />
                </mesh>
                <mesh
                  name="165_4_Av-9_St->Smith-9_Sts_N"
                  castShadow
                  receiveShadow
                  geometry={nodes['165_4_Av-9_St->Smith-9_Sts_N'].geometry}
                  material={materials['Station_G.001']}
                  position={[24.515, -0.053, 19.728]}
                  rotation={[-2.232, -1.538, -2.108]}>
                  <mesh
                    name="GN_Instance_30"
                    castShadow
                    receiveShadow
                    geometry={nodes.GN_Instance_30.geometry}
                    material={materials['Station_G.001']}
                  />
                </mesh>
                <mesh
                  name="165_Smith-9_Sts->4_Av-9_St_S"
                  castShadow
                  receiveShadow
                  geometry={nodes['165_Smith-9_Sts->4_Av-9_St_S'].geometry}
                  material={materials['Station_G.001']}
                  position={[24.578, -0.053, 19.762]}
                  rotation={[-2.232, -1.538, -2.108]}>
                  <mesh
                    name="GN_Instance_31"
                    castShadow
                    receiveShadow
                    geometry={nodes.GN_Instance_31.geometry}
                    material={materials['Station_G.001']}
                  />
                </mesh>
                <mesh
                  name="175_4_7_Av->Av-9_St_ND"
                  castShadow
                  receiveShadow
                  geometry={nodes['175_4_7_Av->Av-9_St_ND'].geometry}
                  material={materials['Station_G.001']}
                  position={[25.48, -0.053, 17.827]}
                  rotation={[-2.232, -1.538, -2.108]}>
                  <mesh
                    name="GN_Instance_32"
                    castShadow
                    receiveShadow
                    geometry={nodes.GN_Instance_32.geometry}
                    material={materials['Station_G.001']}
                  />
                </mesh>
                <mesh
                  name="175_4_Av-9_St->7_Av_S"
                  castShadow
                  receiveShadow
                  geometry={nodes['175_4_Av-9_St->7_Av_S'].geometry}
                  material={materials['Station_G.001']}
                  position={[25.584, -0.053, 17.907]}
                  rotation={[-2.232, -1.538, -2.108]}>
                  <mesh
                    name="GN_Instance_33"
                    castShadow
                    receiveShadow
                    geometry={nodes.GN_Instance_33.geometry}
                    material={materials['Station_G.001']}
                  />
                </mesh>
                <mesh
                  name="185_7_Av->15_St_S"
                  castShadow
                  receiveShadow
                  geometry={nodes['185_7_Av->15_St_S'].geometry}
                  material={materials['Station_G.001']}
                  position={[26.57, -0.053, 16.06]}
                  rotation={[-2.232, -1.538, -2.108]}>
                  <mesh
                    name="GN_Instance_34"
                    castShadow
                    receiveShadow
                    geometry={nodes.GN_Instance_34.geometry}
                    material={materials['Station_G.001']}
                  />
                </mesh>
                <mesh
                  name="185_15_St->7_Av_N"
                  castShadow
                  receiveShadow
                  geometry={nodes['185_15_St->7_Av_N'].geometry}
                  material={materials['Station_G.001']}
                  position={[26.517, -0.053, 15.95]}
                  rotation={[-2.232, -1.538, -2.108]}>
                  <mesh
                    name="GN_Instance_35"
                    castShadow
                    receiveShadow
                    geometry={nodes.GN_Instance_35.geometry}
                    material={materials['Station_G.001']}
                  />
                </mesh>
                <mesh
                  name="195_Ft_Hamilton_Pkwy->15_St_N"
                  castShadow
                  receiveShadow
                  geometry={nodes['195_Ft_Hamilton_Pkwy->15_St_N'].geometry}
                  material={materials['Station_G.001']}
                  position={[28.355, -0.053, 15.939]}
                  rotation={[-2.232, -1.538, -2.108]}>
                  <mesh
                    name="GN_Instance_36"
                    castShadow
                    receiveShadow
                    geometry={nodes.GN_Instance_36.geometry}
                    material={materials['Station_G.001']}
                  />
                </mesh>
                <mesh
                  name="195_Ft_Hamilton_Pkwy->15_St_N001"
                  castShadow
                  receiveShadow
                  geometry={nodes['195_Ft_Hamilton_Pkwy->15_St_N001'].geometry}
                  material={materials['Station_G.001']}
                  position={[28.384, -0.053, 16.019]}
                  rotation={[-2.232, -1.538, -2.108]}>
                  <mesh
                    name="GN_Instance_37"
                    castShadow
                    receiveShadow
                    geometry={nodes.GN_Instance_37.geometry}
                    material={materials['Station_G.001']}
                  />
                </mesh>
                <mesh
                  name="205_Church_Av->Ft_Hamilton_Pkwy_N"
                  castShadow
                  receiveShadow
                  geometry={nodes['205_Church_Av->Ft_Hamilton_Pkwy_N'].geometry}
                  material={materials['Station_G.001']}
                  position={[30.904, -0.053, 15.128]}
                  rotation={[-2.232, -1.538, -2.108]}>
                  <mesh
                    name="GN_Instance_38"
                    castShadow
                    receiveShadow
                    geometry={nodes.GN_Instance_38.geometry}
                    material={materials['Station_G.001']}
                  />
                </mesh>
                <mesh
                  name="205_Ft_Hamilton_Pkwy->Church_Av_S"
                  castShadow
                  receiveShadow
                  geometry={nodes['205_Ft_Hamilton_Pkwy->Church_Av_S'].geometry}
                  material={materials['Station_G.001']}
                  position={[30.862, -0.053, 15.193]}
                  rotation={[-2.232, -1.538, -2.108]}>
                  <mesh
                    name="GN_Instance_39"
                    castShadow
                    receiveShadow
                    geometry={nodes.GN_Instance_39.geometry}
                    material={materials['Station_G.001']}
                  />
                </mesh>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('./public/subway_map_v4.glb')
