"""initial mig models.py

Revision ID: 2cfc682df962
Revises: 
Create Date: 2024-10-08 11:27:26.526769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cfc682df962'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('endpoints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lines', sa.String(), nullable=True),
    sa.Column('endpoint', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_endpoints'))
    )
    op.create_table('stations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gtfs_stop_id', sa.String(), nullable=True),
    sa.Column('station_id', sa.Integer(), nullable=True),
    sa.Column('complex_id', sa.Integer(), nullable=True),
    sa.Column('division', sa.String(), nullable=True),
    sa.Column('line', sa.String(), nullable=True),
    sa.Column('stop_name', sa.String(), nullable=True),
    sa.Column('borough', sa.String(), nullable=True),
    sa.Column('cbd', sa.String(), nullable=True),
    sa.Column('daytime_routes', sa.String(), nullable=True),
    sa.Column('structure', sa.String(), nullable=True),
    sa.Column('gtfs_latitude', sa.String(), nullable=True),
    sa.Column('gtfs_longitude', sa.String(), nullable=True),
    sa.Column('north_direction_label', sa.String(), nullable=True),
    sa.Column('south_direction_label', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stations'))
    )
    op.create_table('riders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('_password_hash', sa.String(), nullable=True),
    sa.Column('fav_subway_activity', sa.String(), nullable=True),
    sa.Column('station_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], name=op.f('fk_riders_station_id_stations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_riders')),
    sa.UniqueConstraint('email', name=op.f('uq_riders_email')),
    sa.UniqueConstraint('username', name=op.f('uq_riders_username'))
    )
    op.create_table('station_endpoints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('route', sa.String(), nullable=True),
    sa.Column('station_name', sa.String(), nullable=True),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('endpoint_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['endpoint_id'], ['endpoints.id'], name=op.f('fk_station_endpoints_endpoint_id_endpoints')),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], name=op.f('fk_station_endpoints_station_id_stations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_station_endpoints'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('station_endpoints')
    op.drop_table('riders')
    op.drop_table('stations')
    op.drop_table('endpoints')
    # ### end Alembic commands ###
