"""added commutes table and relationships

Revision ID: 6ee9c6514333
Revises: 2cfc682df962
Create Date: 2024-10-08 14:13:21.065051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ee9c6514333'
down_revision = '2cfc682df962'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commutes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rider_id', sa.Integer(), nullable=False),
    sa.Column('start_station_id', sa.Integer(), nullable=False),
    sa.Column('end_station_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['end_station_id'], ['stations.id'], name=op.f('fk_commutes_end_station_id_stations')),
    sa.ForeignKeyConstraint(['rider_id'], ['riders.id'], name=op.f('fk_commutes_rider_id_riders')),
    sa.ForeignKeyConstraint(['start_station_id'], ['stations.id'], name=op.f('fk_commutes_start_station_id_stations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_commutes'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('commutes')
    # ### end Alembic commands ###
