"""added rider table and relationships

Revision ID: 799e966814bc
Revises: d0aa14f4885f
Create Date: 2024-10-07 18:05:42.156072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '799e966814bc'
down_revision = 'd0aa14f4885f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('riders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('_password_hash', sa.String(), nullable=True),
    sa.Column('fav_subway_activity', sa.String(), nullable=True),
    sa.Column('station_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], name=op.f('fk_riders_station_id_stations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_riders')),
    sa.UniqueConstraint('username', name=op.f('uq_riders_username'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('riders')
    # ### end Alembic commands ###
