"""added commutetimes table and relationship on commute

Revision ID: 8a084a1b572d
Revises: 6ee9c6514333
Create Date: 2024-10-08 16:35:57.396000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a084a1b572d'
down_revision = '6ee9c6514333'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commute_times',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('commute_id', sa.Integer(), nullable=True, foreign_key='commutes.id'),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('arrival_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_commute_times'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('commute_times')
    # ### end Alembic commands ###
