"""added stationendpoint table and relations with station and endpoint

Revision ID: d0aa14f4885f
Revises: f489e59bcbc3
Create Date: 2024-10-07 17:16:22.728299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0aa14f4885f'
down_revision = 'f489e59bcbc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('station_endpoints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('route', sa.String(), nullable=True),
    sa.Column('station_name', sa.String(), nullable=True),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('endpoint_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['endpoint_id'], ['endpoints.id'], name=op.f('fk_station_endpoints_endpoint_id_endpoints')),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], name=op.f('fk_station_endpoints_station_id_stations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_station_endpoints'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('station_endpoints')
    # ### end Alembic commands ###
