"""added transfer times table

Revision ID: d58374447d83
Revises: d3030de021f6
Create Date: 2025-09-08 18:51:47.390365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd58374447d83'
down_revision = 'd3030de021f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transfer_times',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_stop_id', sa.String(), nullable=True),
    sa.Column('to_stop_id', sa.String(), nullable=True),
    sa.Column('min_transfer_time', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transfer_times'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transfer_times')
    # ### end Alembic commands ###
