"""initial migration

Revision ID: f247e399100a
Revises: 
Create Date: 2024-10-07 16:21:15.500057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f247e399100a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gtfs_stop_id', sa.String(), nullable=True),
    sa.Column('station_id', sa.Integer(), nullable=True),
    sa.Column('complex_id', sa.Integer(), nullable=True),
    sa.Column('division', sa.String(), nullable=True),
    sa.Column('line', sa.String(), nullable=True),
    sa.Column('stop_name', sa.String(), nullable=True),
    sa.Column('borough', sa.String(), nullable=True),
    sa.Column('cbd', sa.String(), nullable=True),
    sa.Column('daytime_routes', sa.String(), nullable=True),
    sa.Column('structure', sa.String(), nullable=True),
    sa.Column('gtfs_latitude', sa.String(), nullable=True),
    sa.Column('gtfs_longitude', sa.String(), nullable=True),
    sa.Column('north_direction_label', sa.String(), nullable=True),
    sa.Column('south_direction_label', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stations'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stations')
    # ### end Alembic commands ###
