"""added endpoints

Revision ID: f489e59bcbc3
Revises: f247e399100a
Create Date: 2024-10-07 17:02:05.424889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f489e59bcbc3'
down_revision = 'f247e399100a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('endpoints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lines', sa.String(), nullable=True),
    sa.Column('endpoint', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_endpoints'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('endpoints')
    # ### end Alembic commands ###
